class BloodGroup
{
public static void main(String[] args)
{
String name="shanta";
System.out.println(name);
String gmail="siraganshantamma@gmail.com";
System.out.println(gmail);
String branch="Information Science & Engineering";
System.out.println(branch);
String cgpa="8.32";
System.out.println(cgpa);
String passOut="2024";
System.out.println(passOut);
String mobileNo="123456789";
System.out.println(mobileNo);
String adress="kalaburgi";
System.out.println(adress);
String college="Godutai Engineering College For Women";
System.out.println(college);
String university="sharnabasva university";
System.out.println(university);
String pincode="585103";
System.out.println(pincode);
String staying="Currently staying in bangalore";
System.out.println(staying);
String area="Rajaaji Nagar";
System.out.println(area);
String distance="6545km";
System.out.println(distance);
String queen="my mother is real queen of home";
System.out.println(queen);
String strength="my dad is my strength";
System.out.println(strength);
String friend="my best friend is only my bestie";
System.out.println(friend);
String shirtSize="S";
System.out.println(shirtSize);
String keywords="48 keywords";
System.out.println(keywords);
String dataTypes="primitive and non-primitive";
System.out.println(dataTypes);
String notes="OracleJava";
System.out.println(notes);
String course="java course";
System.out.println(course);
String program="Hello World";
System.out.println(program);
String fam="family";
System.out.println(fam);
String god="Ganesha";
System.out.println(god);
String colors="fevorite Colores:Pink & Black";
System.out.println(colors);
String fevoriteHero="my fevorite:Rocking star Yash";
System.out.println(fevoriteHero);
String fevoriteHeroien="Radhika Pandit";
System.out.println(fevoriteHeroien);
String movie="Mr & Mrs Ramachari";
System.out.println(movie);
String hobby="lestening moral stories";
System.out.println(hobby);
String trees="save the trees";
System.out.println(trees);
String date="27-06-2024";
System.out.println(date);
String time="03:35";
System.out.println(time);
String mobilePrice="mobile price:15,000rs";
System.out.println(mobilePrice);
String file="notepad++";
System.out.println(file);
String weather="today is rainy";
System.out.println(weather);
String temperature="40 degree celcius";
System.out.println(temperature);
String computer="Hp Computer";
System.out.println(computer);
String generation="12 Generation";
System.out.println(generation);
String busNo="KA326545";
System.out.println(busNo);
String calculator="+,-,*,/";
System.out.println(calculator);
String specialCharacter="!@#$%^&*()_+";
System.out.println(specialCharacter);
String alphabets="A-Z";
System.out.println(alphabets);
String environment="i love nature";
System.out.println(environment);
String animals="i love animals";
System.out.println(animals);
String place="Taj Mahal";
System.out.println(place);
String serial="RadhaKrishna";
System.out.println(serial);
String car="Tesla,BMW,Thar";
System.out.println(car);
String bike="i love Bike Riding";
System.out.println(bike);
String criket="team RCbB";
System.out.println(criket);
String country="India";
System.out.println(country);
String language="Kannada,English,Hindi";
System.out.println(language);
String ref="reference: points to loaction";
System.out.println(ref);
String vari="variable: keeps changing one location to another";
System.out.println(vari);
String str="string: sequence of charactare";
System.out.println(str);
String meta="meta space: meta informatin of classess";
System.out.println(meta);
String consta="constant pool: store all primitive values";
System.out.println(consta);
String stack="stack frame :name of method";
System.out.println(stack);
String proc="process";
System.out.println(proc);
String knowledge="knowledge is power";
System.out.println(knowledge);
String memory="stack-memory";
System.out.println(memory);
String card="Aadhar card";
System.out.println(card);
String pendrive="pendrive";
System.out.println(pendrive);
String carton="Little Krishna";
System.out.println(carton);
String study="read book";
System.out.println(study);
String write="write the program";
System.out.println(write);
String beauty="beautifull";
System.out.println(beauty);
String code="java coding";
System.out.println(code);
String run="runnig the program";
System.out.println(run);
String cmp="compier";
System.out.println(cmp);
String city="Bangalore";
System.out.println(city);
String important="concentration";
System.out.println(important);
String app="Web Applicatin";
System.out.println(app);
String web="Web Developmen";
System.out.println(web);
}
}